name: CI
on: [push, pull_request]

env:
  JRUBY_OPTS: -Xcext.enabled=true

jobs:
  build:
    name: "Test / Ruby ${{ matrix.ruby }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "3.3.0"
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      - name: Install Perl dependencies
        run: |
          curl -1sLf \
            'https://dl.cloudsmith.io/public/nxadm-pkgs/rakudo-pkg/setup.deb.sh' \
            | sudo -E bash
          sudo apt-get update -qq
          sudo apt-get install perl rakudo-pkg

          curl -L http://cpanmin.us | perl - --sudo App::cpanminus
          sudo cpanm --installdeps --notest Pod::Simple

      - name: Run rake
        run: |
          export PATH=$PATH:/.perl6/bin:/opt/rakudo-pkg/bin
          bundle exec rake
